os: osx
osx_image: xcode8
before_install:
  - brew update
install:
  - brew update
  - mkdir -p $(brew --repo)/Library/Taps/travis
  - ln -s $PWD $(brew --repo)/Library/Taps/travis/homebrew-testtap
  - brew tap --repair
env:
  - PACKAGE=sqitch BREW_AUDIT=0 BREW_TEST=0 PERL_CPANM_OPT="--skip-satisfied"
script:
  - if [ "$BREW_AUDIT" = 1 ]; then brew audit $PACKAGE; fi
  - brew install -v $PACKAGE
  - if [ "$BREW_TEST" = 1 ]; then brew test $PACKAGE; fi
